spring.application.name=auth-service

spring.main.banner-mode=off
spring.output.ansi.enabled=ALWAYS

logging.level.org.springframework.security=DEBUG

# ===============================
# = JWT
# ===============================
jwts.keys.private=${JWTS_KEYS_PRIVATE}
jwts.keys.public=${JWTS_KEYS_PUBLIC}

jwts.keys.private.lifetime=${JWTS_KEYS_PRIVATE_TTLMS}
jwts.keys.public.lifetime=${JWTS_KEYS_PUBLIC_TTLMS}

# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
# url for the database "postgres"
spring.datasource.url=${DB_CONNECT}
# Username and password
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
# =========================================
# = Connection Pool
# =========================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000

# ==========================================
# = TOMCAT
# ==========================================
server.port=9000
server.tomcat.threads.max=200
server.tomcat.accept-count=100
server.tomcat.connection-timeout=20000
server.tomcat.uri-encoding=UTF-8