server.port=8300

spring.application.name=driver-service

spring.main.banner-mode=off
spring.output.ansi.enabled=ALWAYS


# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=${DB_CONNECT}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}


# === Eureka Discovery Client ===
spring.cloud.discovery.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL}


